# SPDX-License-Identifier: Apache-2.0
ADD_LIBRARY(capmgr SHARED ${CAPMGR_API_SOURCES})
TARGET_INCLUDE_DIRECTORIES(capmgr
  PUBLIC
    "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>"
    "$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/capmgr>"
  PRIVATE "${PROJECT_SOURCE_DIR}/src"
)
TARGET_LINK_LIBRARIES(capmgr PRIVATE capmgr-adapters Threads::Threads)
SET_TARGET_PROPERTIES(capmgr PROPERTIES
  VERSION ${PROJECT_VERSION}
  SOVERSION 0
  CXX_VISIBILITY_PRESET hidden
  VISIBILITY_INLINES_HIDDEN YES
)
TARGET_LINK_OPTIONS(capmgr PRIVATE
  "LINKER:--version-script=${CMAKE_CURRENT_SOURCE_DIR}/capmgr.map"
)
INSTALL(TARGETS capmgr LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}")
INSTALL(FILES capmgr.h DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/capmgr")

CONFIGURE_FILE("${PROJECT_SOURCE_DIR}/packaging/capability-manager.pc.in"
  "${PROJECT_BINARY_DIR}/capability-manager.pc" @ONLY
)
INSTALL(FILES "${PROJECT_BINARY_DIR}/capability-manager.pc"
  DESTINATION "${CMAKE_INSTALL_LIBDIR}/pkgconfig"
)
