# SPDX-License-Identifier: Apache-2.0
FIND_PACKAGE(SQLite3 REQUIRED)
FIND_PACKAGE(Threads REQUIRED)
IF(CAPMGR_JSON_SOURCE)
  SET(JSON_BuildTests OFF CACHE BOOL "" FORCE)
  ADD_SUBDIRECTORY("${CAPMGR_JSON_SOURCE}" json-dependency EXCLUDE_FROM_ALL)
ELSE()
  FIND_PACKAGE(nlohmann_json 3.10 REQUIRED)
ENDIF()

FIND_PACKAGE(PkgConfig QUIET)
IF(PkgConfig_FOUND)
  PKG_CHECK_MODULES(CYNARA QUIET IMPORTED_TARGET
    cynara-client
    cynara-creds-socket
  )
ENDIF()
IF(CAPMGR_REQUIRE_CYNARA AND NOT CYNARA_FOUND)
  MESSAGE(FATAL_ERROR "Socket-based Cynara development libraries are required")
ENDIF()

FIND_PROGRAM(TIDLC_EXECUTABLE tidlc)
IF(CAPMGR_REQUIRE_TIDL AND NOT TIDLC_EXECUTABLE)
  MESSAGE(FATAL_ERROR "CAPMGR_REQUIRE_TIDL requires tidlc in PATH")
ENDIF()
IF(BUILD_TESTING OR TIDLC_EXECUTABLE)
  FIND_PACKAGE(Python3 REQUIRED COMPONENTS Interpreter)
ENDIF()
IF(BUILD_TESTING)
  FIND_PACKAGE(GTest REQUIRED)
ENDIF()

IF(CAPMGR_BUILD_TIDL_TRANSPORT)
  IF(NOT TIDLC_EXECUTABLE OR NOT CYNARA_FOUND OR NOT PkgConfig_FOUND)
    MESSAGE(FATAL_ERROR
      "TIDL transport requires tidlc and real Cynara development libraries"
    )
  ENDIF()
  PKG_CHECK_MODULES(RPC_PORT REQUIRED IMPORTED_TARGET rpc-port bundle dlog)
  PKG_CHECK_MODULES(GLIB REQUIRED IMPORTED_TARGET glib-2.0)
ENDIF()

IF(CAPMGR_BUILD_AMD_MODULE)
  FIND_PACKAGE(PkgConfig REQUIRED)
  PKG_CHECK_MODULES(AMD REQUIRED IMPORTED_TARGET amd)
  PKG_CHECK_MODULES(DLOG REQUIRED IMPORTED_TARGET dlog)
  PKG_CHECK_MODULES(TZPLATFORM REQUIRED IMPORTED_TARGET libtzplatform-config)
ENDIF()
